### PR TITLE
We dont need this

### PR DESCRIPTION
**Pull request by majst01**
There is no need to push metalctl to images.metal-stack.io, all downloads are available as:
- github release
- docker image

### CODE REVIEW

**Comment by majst01** [comment]
once merged i will remove the content there as well

**Comment by Gerrit91** [comment]
Not exactly sure what's wrong about it having it in two places. Is this somehow problematic? :sweat_smile:

**Comment by majst01** [comment]
Noone uses this download location, we have actually 3 locations where we store the generated binary, i think 2 are enough.
Second: it is unclear if theses files are also synced into the mgmt-server in the partition, which makes deletion of unused objects even harder.

**Comment by Gerrit91** [comment]
Decided to leave it as it is for now because in Germany downloads from Github assets can be terribly slow and pushing it to GCP does not hurt much.

**Pull request closed without merging**
